spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: nico0903
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: cart-service

cart:
  expiration:
    hours: 24

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

logging:
  level:
    com.ecommerce.cart: INFO
    org.springframework: WARN

 
server:
  port: 8083